# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [2]:
import numpy as np

2. Create a null vector of size 10 

In [3]:
x=np.zeros(10)
x


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [4]:
v1=np.arange(10,50)
v1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [5]:
v1.shape


(40,)

5. Print the type of the previous array in question 3

In [6]:
print(type(v1))

<class 'numpy.ndarray'>


6. Print the numpy version and the configuration


In [7]:
print(np.__version__)

1.19.4


7. Print the dimension of the array in question 3


In [8]:
v1.ndim

1

8. Create a boolean array with all the True values

In [9]:
Boolean_array=np.array(True)
Boolean_array

array(True)

9. Create a two dimensional array




In [10]:
two_dim=np.arange(12).reshape((3, 4))
np.array(two_dim)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

10. Create a three dimensional array



In [11]:
three_dim=np.arange(24).reshape((2, 3, 4))
three_dim

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [12]:
v1
print(v1)
print(np.flip(v1))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


12. Create a null vector of size 10 but the fifth value which is 1 

In [13]:
x[4]=1
print(x)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


13. Create a 3x3 identity matrix

In [14]:
ide=np.eye(3)
ide

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [15]:
arr = np.array([1, 2, 3, 4, 5])
arr = arr.astype('float64') 
print(arr)
print(arr.dtype) 

[1. 2. 3. 4. 5.]
float64


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [16]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
product=arr1*arr2
print(product)

[[ 0.  8.  3.]
 [28. 10. 72.]]


16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [17]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])
arr3=arr1==arr2
arr3

array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [18]:
odd=np.arange(0,9)
print(odd[odd % 2 == 1])


[1 3 5 7]


18. Replace all odd numbers to -1 from previous array

In [19]:
odd=np.arange(0,9)
odd_no=(odd % 2 == 1)
odd[odd_no]=-1
odd




array([ 0, -1,  2, -1,  4, -1,  6, -1,  8])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [20]:
arr = np.arange(10)
arr[5:9]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [21]:
x = np.ones((3,3))
print(x)
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [22]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 
 
            [7, 8, 9]])
arr2d[1,1]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [23]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0:1,0:1]=64
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [24]:
arr2d = np.arange(9).reshape(3,3)
print(arr2d)
arr_slice=arr2d[0:1,0:3]
print("first 1st 1-D array ")
print(arr_slice)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
first 1st 1-D array 
[[0 1 2]]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [25]:
arr2d = np.arange(9).reshape(3,3)
print(arr2d)
arr_slice=arr2d[1:2,1:2]
print("2nd value from 2nd 1-D array")
arr_slice

[[0 1 2]
 [3 4 5]
 [6 7 8]]
2nd value from 2nd 1-D array


array([[4]])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [26]:
arr2d = np.arange(9).reshape(3,3)
print(arr2d)
arr_slice=arr2d[0:2,2:]
print("2nd value from 2nd 1-D array")
arr_slice

[[0 1 2]
 [3 4 5]
 [6 7 8]]
2nd value from 2nd 1-D array


array([[2],
       [5]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [27]:
x = np.random.random((5,5))
print(x)
print(x.max())
print(x.min())

[[0.74771165 0.09438226 0.07801943 0.74511299 0.43794301]
 [0.9739221  0.05358115 0.42794932 0.01625491 0.61107116]
 [0.67092448 0.67447835 0.05526536 0.18061026 0.12009138]
 [0.226543   0.33695686 0.99507614 0.30295043 0.25544588]
 [0.59470371 0.02373984 0.18658689 0.42509094 0.3224825 ]]
0.9950761418414431
0.0162549079895441


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [28]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

print("Common values between two arrays:")
print(np.intersect1d(a,b))

Common values between two arrays:
[2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [29]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

print("Common values between two arrays:")
print(np.where((np.intersect1d(a,b))))

Common values between two arrays:
(array([0, 1]),)


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [30]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(names)
data = np.random.randn(7, 4)
print(data)
print("all the values from array data where the values from array names are not equal to Will")
print(data[names!="Will"])

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[-0.39811962  0.73884722  0.80724435 -1.00057255]
 [-0.00857319  0.67850796 -0.11904881 -1.75650853]
 [-0.38794256 -1.852041    0.62287252  0.547771  ]
 [-1.01909858  2.07120329  0.44441356  0.23468357]
 [ 0.63354367 -0.17121677  0.29956671  0.094272  ]
 [-1.06139048  2.69823961  0.77997965  1.86554739]
 [ 1.74848499  0.62230724  0.37350247  2.17644145]]
all the values from array data where the values from array names are not equal to Will
[[-0.39811962  0.73884722  0.80724435 -1.00057255]
 [-0.00857319  0.67850796 -0.11904881 -1.75650853]
 [-1.01909858  2.07120329  0.44441356  0.23468357]
 [-1.06139048  2.69823961  0.77997965  1.86554739]
 [ 1.74848499  0.62230724  0.37350247  2.17644145]]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [31]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print("all the values from array data where the values from array names are not equal to Will")
print(data[names!="Will"])
print("all the values from array data where the values from array names are not equal to Joe")
print(data[names!="Joe"])

all the values from array data where the values from array names are not equal to Will
[[-1.23867816  0.50173252  0.58293113 -0.33419348]
 [-2.78116899  0.54308476  0.69763432 -1.17848369]
 [-1.7241338  -1.03940585  0.61344118 -0.10805266]
 [ 0.41466177 -0.44281972  1.19734829  0.25492216]
 [ 0.33826194  0.99262466  0.85972856  0.55889892]]
all the values from array data where the values from array names are not equal to Joe
[[-1.23867816  0.50173252  0.58293113 -0.33419348]
 [-1.49119478 -0.55431    -0.50451989 -0.77645551]
 [-1.7241338  -1.03940585  0.61344118 -0.10805266]
 [ 0.28692239  0.38891658  1.39669152  0.51112707]]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [32]:
rand_arr = np.random.uniform(1,15, size=(5,3))
rand_arr


array([[ 8.72860552, 11.35377435,  8.40969902],
       [ 9.26861818,  8.8212559 , 10.50305147],
       [13.62834055, 13.77639404,  9.13218089],
       [ 9.33651572, 12.35652038, 13.66877444],
       [ 1.94372783, 11.53969198,  2.34672636]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [33]:
rand_arr = np.random.uniform(1,16, size=(2,2,4))
rand_arr

array([[[ 1.58564971,  4.13821734, 11.90301912, 11.14597692],
        [14.54763194, 14.42800154,  6.3906454 , 15.01609264]],

       [[ 3.58634475,  7.7026899 ,  7.92897584,  6.36376826],
        [13.09678455, 10.03205887, 13.34701662,  1.54562881]]])

33. Swap axes of the array you created in Question 32

In [34]:
rand_arr = np.random.uniform(1,16, size=(2,2,4))
print(rand_arr)
rand_arr=np.swapaxes(rand_arr,0,2)
print("after swapping")
print(rand_arr)


[[[ 6.14359245  8.7982495   8.61321235  5.07660675]
  [11.18777907  2.71802271  9.97990856 10.90554239]]

 [[11.91842453 12.9035243  14.99385843  8.09598595]
  [ 4.47475136 11.85466439 11.22242621  1.50438629]]]
after swapping
[[[ 6.14359245 11.91842453]
  [11.18777907  4.47475136]]

 [[ 8.7982495  12.9035243 ]
  [ 2.71802271 11.85466439]]

 [[ 8.61321235 14.99385843]
  [ 9.97990856 11.22242621]]

 [[ 5.07660675  8.09598595]
  [10.90554239  1.50438629]]]


34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [35]:

arr1 = np.random.randn(10)
square_arr1 = arr1 * arr1
print(square_arr1)
x=0
for i in square_arr1:
    if i<0.5:
        square_arr1[x]=0
    x=x+1
square_arr1


[2.51372769 0.59818954 0.45518577 0.46340602 1.64205874 1.11816056
 0.00701016 0.12012105 0.02357993 0.25067254]


array([2.51372769, 0.59818954, 0.        , 0.        , 1.64205874,
       1.11816056, 0.        , 0.        , 0.        , 0.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [36]:
arr1 = np.random.randn(10)
arr2 = np.random.randn(10)
arr3=np.maximum(arr1,arr2)
arr3

array([ 0.35012093,  0.63755152,  2.90962567,  1.004159  ,  0.46785473,
       -0.68123074,  0.2661273 ,  0.62885232,  1.07435259, -1.53363256])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [37]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [38]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
a= np.setdiff1d(a,b)
a

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [39]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
print(sampleArray)
newColumn = np.array([[10,10,10]])
sampleArray[0,:] = newColumn
sampleArray

[[34 43 73]
 [82 22 12]
 [53 94 66]]


array([[10, 10, 10],
       [82, 22, 12],
       [53, 94, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [40]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [41]:
rand = np.random.randn(20)
print(rand)
sum(rand)

[-2.57169769  0.67705919 -0.29018555 -1.21535527 -1.5718413   1.61252963
 -1.05076281  1.04397544  0.01148216 -1.16250792 -1.33921726 -1.15844359
  0.11639604  1.13752372  0.40544971  0.27702445  1.07433075 -0.60307224
  1.19067187  0.2955862 ]


-3.1210544669501634