<a href="https://colab.research.google.com/github/adikhan99/PIAIC-Assignment/blob/main/Assignment_2(Numpy_Fundamentals)_PIAIC89200.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy_Assignment_2::

In [1]:
import numpy as np

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [32]:
a=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
a=np.reshape(a,(2,5))
print("2D array with 2  rows")
print(a)


2D array with 2  rows
[[0 1 2 3 4]
 [5 6 7 8 9]]


## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [33]:
a1=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]).reshape(2,5)
a2=np.array([10,11, 12, 13, 14, 15, 16, 17, 18, 19]).reshape(2,5)
print("stacking two arrays vertically")
print(np.vstack((a1,a2)))


stacking two arrays vertically
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [34]:
a1=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
a2=np.array([10,11, 12, 13, 14, 15, 16, 17, 18, 19])
print("stacking two arrays horizontally")
print(np.vstack((a1,a2)))


stacking two arrays horizontally
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
b=np.vstack((a1,a2))
print("converting into 1D array")
print(np.ravel(b))

converting into 1D array
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

In [37]:
print("converting higher dimension into one dimension")
print(np.array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],[10,11,12,13,14]]).ravel())

converting higher dimension into one dimension
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

array([[ 0, 1, 2],
[ 3, 4, 5],
[ 6, 7, 8],
[ 9, 10, 11],
[12, 13, 14]])

In [14]:
np.array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]).reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [41]:
x=np.random.randn(25).reshape(5,5)*5
np.array(x)
x=np.square(x)
print("Square of 5x5 array " )
print(x)

Square of 5x5 array 
[[1.29747022e+01 2.85792794e+01 5.34247867e+00 3.77328545e+01
  1.39941773e+00]
 [2.07394600e+01 2.44966707e+01 1.12937499e+02 2.25843413e+01
  4.56179551e+01]
 [4.12007734e+01 2.22094955e+01 1.31886587e+01 6.22530544e+01
  2.72754138e+00]
 [3.47253123e+00 5.69818270e+01 1.59822615e+00 4.44846152e+01
  4.23189194e-02]
 [4.07619540e+01 5.09494354e+01 7.95963529e+00 1.55242311e+01
  4.73290424e+00]]


## Question:8

### Create 5x6 an array and find the mean?

In [45]:
y=np.random.randn(25).reshape(5,5)*5
y=np.array(y)
m=np.mean(y)
print("mean of 5x6 array")
print(m)


mean of 5x6 array
0.63778342177948


## Question:9

### Find the standard deviation of the previous array in Q8?

In [46]:
print("standard deviation")
print(np.std(y))

standard deviation
5.456385191194171


## Question:10

### Find the median of the previous array in Q8?

In [47]:
print("median")
np.median(y)

median


0.494885910659303

## Question:11

### Find the transpose of the previous array in Q8?

In [49]:
print("Transpose")
y.T

Transpose


array([[  2.3542028 ,   0.49488591,  -2.19120187,  -4.21031328,
          5.28386875],
       [ 15.83069093,  -1.50694618, -11.55103676,  -5.03374468,
         -1.84675979],
       [  6.32348853,   5.43448881,   6.68102015,   2.47290013,
          3.06506842],
       [ -1.76086197,   1.86597579,  -6.6045216 ,   1.32297658,
          4.83163029],
       [ -0.88622651,   5.92062346,  -5.45263506,  -1.86484933,
         -3.02813794]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [54]:
z=np.random.randn(16).reshape(4,4)*5
z=np.array(z)
print('4x4 array')
print(z)
np.diagonal(z)
print("sum of diagonal elements")
np.diagonal(z).sum()

4x4 array
[[ 9.29060752 -4.30145857  3.93875664  8.33811851]
 [-4.32552815 -1.76901399  1.01994489  0.01103503]
 [ 1.07257518  4.5071077  -4.47954457  1.00321919]
 [ 7.06498084 -3.44048551 -3.36872217 -3.32901194]]
sum of diagonal elements


-0.2869629756777341

## Question:13

### Find the determinant of the previous array in Q12?

In [55]:
print("determinant")
np.linalg.det(z)

determinant


-1580.328663352048

## Question:14

### Find the 5th and 95th percentile of an array?

In [56]:
print(z)
print("5th percentile",np.percentile(z, 5))
print("95th percentile",np.percentile(z, 95))

[[ 9.29060752 -4.30145857  3.93875664  8.33811851]
 [-4.32552815 -1.76901399  1.01994489  0.01103503]
 [ 1.07257518  4.5071077  -4.47954457  1.00321919]
 [ 7.06498084 -3.44048551 -3.36872217 -3.32901194]]
5th percentile -4.364032251046409
95th percentile 8.576240765055635


## Question:15

### How to find if a given array has any null values?

In [57]:
null= np.array([[1,2,3,4],
              [2,3,np.nan,5],
              [np.nan,5,2,3]])
np.argwhere(np.isnan(null))



array([[1, 2],
       [2, 0]])